language: python

sudo: false

python:
  - "2.7"

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy, scipy
  - python setup.py install

script:
  - python setup.py test